spring.application.name=MultiDB
server.port=8181

# Primary Database (MySQL Example)
spring.datasource.primary.jdbc-url=jdbc:mysql://localhost:3306/users
spring.datasource.primary.username=root
spring.datasource.primary.password=Mysql@2026
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver


#JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Secondary Database (PostgreSQL Example)
spring.datasource.secondary.jdbc-url=jdbc:postgresql://localhost:5432/secondary_db
spring.datasource.secondary.username=postgres
spring.datasource.secondary.password=secret
spring.datasource.secondary.driver-class-name=org.postgresql.Driver






